type SimulatedYellowCardMarketEntry = {
  countryCode: string;
  countryName: string;
  currency: string;
  currencyName: string;
  symbol: string;
  channelType: "bank" | "momo";
  networkCode: string;
  networkName: string;
  accountNumberType: "bank" | "momo";
  countryAccountNumberType: string;
  rateLocalPerUsd: number;
  feeLocal: number;
  feeUsd: number;
  min: number;
  max: number;
  widgetMin: number;
  widgetMax: number;
  estimatedSettlementTime: number;
};

const simulatedYellowCardMarketCatalog: SimulatedYellowCardMarketEntry[] = [
  {
    countryCode: "NG",
    countryName: "Nigeria",
    currency: "NGN",
    currencyName: "Nigerian naira",
    symbol: "NGN",
    channelType: "bank",
    networkCode: "044",
    networkName: "Access Bank",
    accountNumberType: "bank",
    countryAccountNumberType: "NGBANK",
    rateLocalPerUsd: 1555,
    feeLocal: 185.2,
    feeUsd: 1.2,
    min: 100,
    max: 5000000,
    widgetMin: 100,
    widgetMax: 100000,
    estimatedSettlementTime: 60,
  },
  {
    countryCode: "GH",
    countryName: "Ghana",
    currency: "GHS",
    currencyName: "Ghanaian cedi",
    symbol: "GHS",
    channelType: "momo",
    networkCode: "MTN",
    networkName: "MTN Ghana",
    accountNumberType: "momo",
    countryAccountNumberType: "GHMOMO",
    rateLocalPerUsd: 15.8,
    feeLocal: 12,
    feeUsd: 0.8,
    min: 25,
    max: 250000,
    widgetMin: 25,
    widgetMax: 5000,
    estimatedSettlementTime: 45,
  },
  {
    countryCode: "KE",
    countryName: "Kenya",
    currency: "KES",
    currencyName: "Kenyan shilling",
    symbol: "KES",
    channelType: "bank",
    networkCode: "01",
    networkName: "KCB Kenya",
    accountNumberType: "bank",
    countryAccountNumberType: "KEBANK",
    rateLocalPerUsd: 129.5,
    feeLocal: 85,
    feeUsd: 0.6,
    min: 50,
    max: 350000,
    widgetMin: 50,
    widgetMax: 7500,
    estimatedSettlementTime: 50,
  },
  {
    countryCode: "ZM",
    countryName: "Zambia",
    currency: "ZMW",
    currencyName: "Zambian kwacha",
    symbol: "ZMW",
    channelType: "bank",
    networkCode: "01",
    networkName: "Zanaco",
    accountNumberType: "bank",
    countryAccountNumberType: "ZMBANK",
    rateLocalPerUsd: 27.4,
    feeLocal: 18,
    feeUsd: 0.9,
    min: 20,
    max: 80000,
    widgetMin: 20,
    widgetMax: 2500,
    estimatedSettlementTime: 90,
  },
  {
    countryCode: "UG",
    countryName: "Uganda",
    currency: "UGX",
    currencyName: "Ugandan shilling",
    symbol: "UGX",
    channelType: "momo",
    networkCode: "MTN",
    networkName: "MTN Uganda",
    accountNumberType: "momo",
    countryAccountNumberType: "UGMOMO",
    rateLocalPerUsd: 3875,
    feeLocal: 2900,
    feeUsd: 0.75,
    min: 1000,
    max: 5000000,
    widgetMin: 1000,
    widgetMax: 180000,
    estimatedSettlementTime: 50,
  },
  {
    countryCode: "TZ",
    countryName: "Tanzania",
    currency: "TZS",
    currencyName: "Tanzanian shilling",
    symbol: "TZS",
    channelType: "bank",
    networkCode: "01",
    networkName: "NMB Bank",
    accountNumberType: "bank",
    countryAccountNumberType: "TZBANK",
    rateLocalPerUsd: 2620,
    feeLocal: 2100,
    feeUsd: 0.8,
    min: 1500,
    max: 4500000,
    widgetMin: 1500,
    widgetMax: 160000,
    estimatedSettlementTime: 75,
  },
  {
    countryCode: "RW",
    countryName: "Rwanda",
    currency: "RWF",
    currencyName: "Rwandan franc",
    symbol: "RWF",
    channelType: "momo",
    networkCode: "MTN",
    networkName: "MTN Rwanda",
    accountNumberType: "momo",
    countryAccountNumberType: "RWMOMO",
    rateLocalPerUsd: 1325,
    feeLocal: 950,
    feeUsd: 0.72,
    min: 500,
    max: 1500000,
    widgetMin: 500,
    widgetMax: 90000,
    estimatedSettlementTime: 45,
  },
  {
    countryCode: "MW",
    countryName: "Malawi",
    currency: "MWK",
    currencyName: "Malawian kwacha",
    symbol: "MWK",
    channelType: "bank",
    networkCode: "01",
    networkName: "National Bank of Malawi",
    accountNumberType: "bank",
    countryAccountNumberType: "MWBANK",
    rateLocalPerUsd: 1730,
    feeLocal: 1350,
    feeUsd: 0.78,
    min: 1000,
    max: 2800000,
    widgetMin: 1000,
    widgetMax: 125000,
    estimatedSettlementTime: 95,
  },
  {
    countryCode: "BW",
    countryName: "Botswana",
    currency: "BWP",
    currencyName: "Botswana pula",
    symbol: "BWP",
    channelType: "bank",
    networkCode: "01",
    networkName: "First National Bank Botswana",
    accountNumberType: "bank",
    countryAccountNumberType: "BWBANK",
    rateLocalPerUsd: 13.8,
    feeLocal: 8.4,
    feeUsd: 0.61,
    min: 15,
    max: 120000,
    widgetMin: 15,
    widgetMax: 6500,
    estimatedSettlementTime: 80,
  },
  {
    countryCode: "ZA",
    countryName: "South Africa",
    currency: "ZAR",
    currencyName: "South African rand",
    symbol: "ZAR",
    channelType: "bank",
    networkCode: "632005",
    networkName: "ABSA Bank",
    accountNumberType: "bank",
    countryAccountNumberType: "ZABANK",
    rateLocalPerUsd: 18.7,
    feeLocal: 14.6,
    feeUsd: 0.78,
    min: 20,
    max: 150000,
    widgetMin: 20,
    widgetMax: 8000,
    estimatedSettlementTime: 85,
  },
  {
    countryCode: "CD",
    countryName: "Democratic Republic of the Congo",
    currency: "CDF",
    currencyName: "Congolese franc",
    symbol: "CDF",
    channelType: "bank",
    networkCode: "01",
    networkName: "Rawbank",
    accountNumberType: "bank",
    countryAccountNumberType: "CDBANK",
    rateLocalPerUsd: 2850,
    feeLocal: 2200,
    feeUsd: 0.77,
    min: 1000,
    max: 4200000,
    widgetMin: 1000,
    widgetMax: 140000,
    estimatedSettlementTime: 105,
  },
  {
    countryCode: "CI",
    countryName: "Ivory Coast",
    currency: "XOF",
    currencyName: "West African CFA franc",
    symbol: "XOF",
    channelType: "bank",
    networkCode: "SGCI",
    networkName: "Societe Generale CI",
    accountNumberType: "bank",
    countryAccountNumberType: "CIBANK",
    rateLocalPerUsd: 620,
    feeLocal: 420,
    feeUsd: 0.68,
    min: 250,
    max: 750000,
    widgetMin: 250,
    widgetMax: 30000,
    estimatedSettlementTime: 95,
  },
  {
    countryCode: "SN",
    countryName: "Senegal",
    currency: "XOF",
    currencyName: "West African CFA franc",
    symbol: "XOF",
    channelType: "momo",
    networkCode: "ORANGE",
    networkName: "Orange Money Senegal",
    accountNumberType: "momo",
    countryAccountNumberType: "SNMOMO",
    rateLocalPerUsd: 620,
    feeLocal: 430,
    feeUsd: 0.69,
    min: 250,
    max: 750000,
    widgetMin: 250,
    widgetMax: 30000,
    estimatedSettlementTime: 55,
  },
  {
    countryCode: "BJ",
    countryName: "Benin",
    currency: "XOF",
    currencyName: "West African CFA franc",
    symbol: "XOF",
    channelType: "momo",
    networkCode: "MTN",
    networkName: "MTN Benin",
    accountNumberType: "momo",
    countryAccountNumberType: "BJMOMO",
    rateLocalPerUsd: 620,
    feeLocal: 430,
    feeUsd: 0.69,
    min: 250,
    max: 750000,
    widgetMin: 250,
    widgetMax: 30000,
    estimatedSettlementTime: 55,
  },
  {
    countryCode: "TG",
    countryName: "Togo",
    currency: "XOF",
    currencyName: "West African CFA franc",
    symbol: "XOF",
    channelType: "momo",
    networkCode: "TOGOCEL",
    networkName: "Togo Celulaire",
    accountNumberType: "momo",
    countryAccountNumberType: "TGMOMO",
    rateLocalPerUsd: 620,
    feeLocal: 430,
    feeUsd: 0.69,
    min: 250,
    max: 750000,
    widgetMin: 250,
    widgetMax: 30000,
    estimatedSettlementTime: 55,
  },
  {
    countryCode: "BF",
    countryName: "Burkina Faso",
    currency: "XOF",
    currencyName: "West African CFA franc",
    symbol: "XOF",
    channelType: "momo",
    networkCode: "MOOV",
    networkName: "Moov Burkina Faso",
    accountNumberType: "momo",
    countryAccountNumberType: "BFMOMO",
    rateLocalPerUsd: 620,
    feeLocal: 430,
    feeUsd: 0.69,
    min: 250,
    max: 750000,
    widgetMin: 250,
    widgetMax: 30000,
    estimatedSettlementTime: 55,
  },
  {
    countryCode: "ML",
    countryName: "Mali",
    currency: "XOF",
    currencyName: "West African CFA franc",
    symbol: "XOF",
    channelType: "bank",
    networkCode: "BMS",
    networkName: "Banque Malienne de Solidarite",
    accountNumberType: "bank",
    countryAccountNumberType: "MLBANK",
    rateLocalPerUsd: 620,
    feeLocal: 420,
    feeUsd: 0.68,
    min: 250,
    max: 750000,
    widgetMin: 250,
    widgetMax: 30000,
    estimatedSettlementTime: 95,
  },
  {
    countryCode: "CM",
    countryName: "Cameroon",
    currency: "XAF",
    currencyName: "Central African CFA franc",
    symbol: "XAF",
    channelType: "bank",
    networkCode: "SCB",
    networkName: "Standard Chartered Cameroon",
    accountNumberType: "bank",
    countryAccountNumberType: "CMBANK",
    rateLocalPerUsd: 605,
    feeLocal: 410,
    feeUsd: 0.67,
    min: 250,
    max: 720000,
    widgetMin: 250,
    widgetMax: 28000,
    estimatedSettlementTime: 95,
  },
  {
    countryCode: "CG",
    countryName: "Congo Brazzaville",
    currency: "XAF",
    currencyName: "Central African CFA franc",
    symbol: "XAF",
    channelType: "momo",
    networkCode: "AIRTEL",
    networkName: "Airtel Congo",
    accountNumberType: "momo",
    countryAccountNumberType: "CGMOMO",
    rateLocalPerUsd: 605,
    feeLocal: 415,
    feeUsd: 0.68,
    min: 250,
    max: 720000,
    widgetMin: 250,
    widgetMax: 28000,
    estimatedSettlementTime: 60,
  },
  {
    countryCode: "GA",
    countryName: "Gabon",
    currency: "XAF",
    currencyName: "Central African CFA franc",
    symbol: "XAF",
    channelType: "bank",
    networkCode: "BICIG",
    networkName: "BICIG",
    accountNumberType: "bank",
    countryAccountNumberType: "GABANK",
    rateLocalPerUsd: 605,
    feeLocal: 410,
    feeUsd: 0.67,
    min: 250,
    max: 720000,
    widgetMin: 250,
    widgetMax: 28000,
    estimatedSettlementTime: 95,
  },
];

export type SimulatedYellowCardMarket = SimulatedYellowCardMarketEntry;

export function listSimulatedYellowCardMarkets(country?: string) {
  return country
    ? simulatedYellowCardMarketCatalog.filter((entry) => entry.countryCode === country)
    : simulatedYellowCardMarketCatalog;
}

export function getSimulatedYellowCardMarketByCurrency(currency: string) {
  return simulatedYellowCardMarketCatalog.find((entry) => entry.currency === currency) ?? null;
}

export function getSimulatedYellowCardCurrencyMetadata(currency: string) {
  const entry = getSimulatedYellowCardMarketByCurrency(currency);

  if (!entry) {
    return null;
  }

  const countryNames = Array.from(
    new Set(
      simulatedYellowCardMarketCatalog
        .filter((candidate) => candidate.currency === currency)
        .map((candidate) => candidate.countryName)
    )
  );

  return {
    currency: entry.currency,
    currencyName: entry.currencyName,
    symbol: entry.symbol,
    countryNames,
  };
}
